language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be install"
before_script:
  - echo "no tests"

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed raphman8/udagram-api-feed:v2
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user raphman8/udagram-api-user:v2
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy raphman8/udagram-reverseproxy:v2
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend raphman8/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push raphman8/udagram-api-feed:v2
  - docker push raphman8/udagram-api-user:v2
  - docker push raphman8/udagram-reverseproxy:v2
  - docker push raphman8/udagram-frontend:v2
