apiVersion: v1
kind: Deployment
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
       # Define the environment variable
        - name: BUCKET
          valueFrom:
            configMapKeyRef:
               name: env-configmap
               key: bucket
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: postgres